# Site settings
title: Law Office of Eloise Hock Feinstein
email: eloise@lawehf.com
description: Law Office of Eloise Hock Feinstein
baseurl: ""
url: "http://www.lawehf.com"
homeurl: "/home/"

javascripts:
  - //ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js
  - //ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-route.js
  - //cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.0/ui-bootstrap-tpls.js

addresses:
  street: "11622 El Camino Real #100 San Diego CA 92130"
  mailing: "12463 Rancho Bernardo Rd #238 San Diego CA 92128"

numbers:
  phone: (858) 224-2343
  fax: (858) 876-1641

# Build settings
markdown: kramdown
